[colors.bright]
black = "#598489"
blue = "#009AFB"
cyan = "#5FFFFF"
green = "#00FF9A"
magenta = "#FF578F"
red = "#E65029"
white = "#D9FBFF"
yellow = "#E89440"

[colors.normal]
black = "#6A787A"
blue = "#44AAE6"
cyan = "#3DD5E7"
green = "#39E9A8"
magenta = "#E17599"
red = "#E9653B"
white = "#C3DDE1"
yellow = "#E5B684"

[colors.primary]
background = "#1E1E1E"
foreground = "#CCCCCC"

[cursor.style]
shape = "Beam"

[env]
term = "xterm-256color"

[font]
size = 15

[mouse]
hide_when_typing = true
